#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyCoffeeApp.Droid.Resource", IsApplication=true)]

namespace MyCoffeeApp.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.0.0.73")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int launcher_background = 2130771972;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020011
			public const int about = 2130837521;
			
			// aapt resource value: 0x7F020000
			public const int AboutIcon = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int AccessoriesIcon = 2130837505;
			
			// aapt resource value: 0x7F020012
			public const int addIcon = 2130837522;
			
			// aapt resource value: 0x7F020002
			public const int AddToCartIcon = 2130837506;
			
			// aapt resource value: 0x7F020013
			public const int adduser = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int asian_dolce_latte = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int asset_vanilla_latte = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int backarrowicon = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int backicon = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int bookticket = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int brandcoffee = 2130837529;
			
			// aapt resource value: 0x7F020003
			public const int BuyIcon = 2130837507;
			
			// aapt resource value: 0x7F02001B
			public const int caffee_latte = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int caffee_mocha = 2130837532;
			
			// aapt resource value: 0x7F02001A
			public const int caffe_americano = 2130837530;
			
			// aapt resource value: 0x7F02001D
			public const int cf = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int coffee1 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int coffeebag = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int contact = 2130837536;
			
			// aapt resource value: 0x7F020004
			public const int DeleteIcon = 2130837508;
			
			// aapt resource value: 0x7F020021
			public const int espresso = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int espresso_con_panna = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int espresso_macchiato = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int favorite = 2130837540;
			
			// aapt resource value: 0x7F020005
			public const int FavouriteBlack = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int FavouriteBlackIcon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int FavouriteIcon = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int FavouriteRed = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int FavouriteRedIcon = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int HelpIcon = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int HomeIcon = 2130837515;
			
			// aapt resource value: 0x7F020025
			public const int iced_caffe_americano = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int icon_about = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int icon_feed = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int login = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int loginuser = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int logout = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int menuicon = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int payment = 2130837548;
			
			// aapt resource value: 0x7F02000C
			public const int Pin = 2130837516;
			
			// aapt resource value: 0x7F02002D
			public const int playicon = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int reserve = 2130837550;
			
			// aapt resource value: 0x7F02000D
			public const int Samsung_Galaxy_S22_Ultra = 2130837517;
			
			// aapt resource value: 0x7F02002F
			public const int save = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int search = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int settings = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int signup = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int skinny_flavored_latte = 2130837555;
			
			// aapt resource value: 0x7F02000E
			public const int SmartphoneIcon = 2130837518;
			
			// aapt resource value: 0x7F020034
			public const int star = 2130837556;
			
			// aapt resource value: 0x7F02000F
			public const int UITLogo = 2130837519;
			
			// aapt resource value: 0x7F020035
			public const int uploadImage = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int xamarin_logo = 2130837558;
			
			// aapt resource value: 0x7F020010
			public const int Xiaomi_11T_Pro_5G = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050003
			public const int icon = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int icon_round = 2131034116;
			
			// aapt resource value: 0x7F050000
			public const int ic_launcher = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int ic_launcher_foreground = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int ic_launcher_round = 2131034114;
			
			// aapt resource value: 0x7F050005
			public const int launcher_foreground = 2131034117;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int MainTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
